src/Entity/Peinture.php
<?php

namespace App\Entity;

use App\Repository\PeintureRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PeintureRepository::class)]
class Peinture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le titre est obligatoire.")]
    #[Assert\Length(
        min: 3,
        max: 255,
        minMessage: "Le titre doit contenir au moins {{ limit }} caractères.",
        maxMessage: "Le titre ne peut pas dépasser {{ limit }} caractères."
    )]

    #[Assert\Regex(
        pattern: "/^[a-zA-ZÀ-ÿ\s]+$/u",
        message: "Le titre ne doit contenir que des lettres et des espaces."
    )]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotNull(message: "La date de création est obligatoire.")]
    #[Assert\LessThanOrEqual("today", message: "La date de création ne peut pas être dans le futur.")]
    private ?\DateTimeInterface $date_cr = null;

    #[ORM\Column(length: 255)]
    //#[Assert\NotNull(message: "Le tableau est obligatoire.")]
    private ?string $tableau = null;

    #[ORM\ManyToOne(inversedBy: 'peintures')]
    private ?Style $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateCr(): ?\DateTimeInterface
    {
        return $this->date_cr;
    }

    public function setDateCr(\DateTimeInterface $date_cr): static
    {
        $this->date_cr = $date_cr;

        return $this;
    }

    public function getTableau(): ?string
    {
        return $this->tableau;
    }

    public function setTableau(string $tableau): static
    {
        $this->tableau = $tableau;

        return $this;
    }

    public function getType(): ?Style
    {
        return $this->type;
    }

    public function setType(?Style $type): static
    {
        $this->type = $type;

        return $this;
    }
}

src/Entity/User.php
<?php
// src/Entity/User.php
namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\NotBlank(message: "L'email est obligatoire.")]
    #[Assert\Email(message: "L'email '{{ value }}' n'est pas valide.")]
    private ?string $email;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\NotBlank(message: "Le nom est obligatoire.")]
    #[Assert\Length(min: 2, max: 50, minMessage: "Le nom doit contenir au moins 2 caractères.", maxMessage: "Le nom ne peut pas dépasser 50 caractères.")]
    private string $nom;

    #[ORM\Column(type: 'string', length: 50)]
    #[Assert\NotBlank(message: "Le prénom est obligatoire.")]
    #[Assert\Length(min: 2, max: 50, minMessage: "Le prénom doit contenir au moins 2 caractères.", maxMessage: "Le prénom ne peut pas dépasser 50 caractères.")]
    private string $prenom;

    #[ORM\Column(type: 'string', length: 10)]
    #[Assert\NotBlank(message: "Le genre est obligatoire.")]
    #[Assert\Choice(choices: ['Homme', 'Femme'], message: "Le genre doit être 'Homme' ou 'Femme'.")]
    private string $genre;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    #[ORM\Column(type: 'string')]
    private string $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    public function getNom(): string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;
        return $this;
    }

    public function getPrenom(): string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;
        return $this;
    }

    public function getGenre(): string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;
        return $this;
    }

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;
use App\Entity\User;
use App\Entity\Musique;
use App\Entity\Peinture;
use App\Entity\Playlist;
use App\Entity\Style;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Form\AddUserType;
use App\Form\EditUserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Form\ModifierProfileType;
use App\Form\ModifierProfileAdminType;
use App\Repository\MusiqueRepository;
use App\Repository\PeintureRepository;
use App\Repository\StyleRepository;
use App\Form\AddEditPeintureType;



class UserController extends AbstractController
{
    #[Route('/admin', name: 'app_admin')]
    public function index(): Response
    {
        $user = $this->getUser();       
        return $this->render('user/dashboard.html.twig', [
            'controller_name' => 'UserController',
            'user' => $user
        ]);
    }    
    #[Route('/dash', name: 'app_dash')]
    public function dash(): Response
    {
        $user = $this->getUser();       
        return $this->render('Back.html.twig', [
            'controller_name' => 'UserController',
            'user' => $user
        ]);
    }
    #[Route('/profile/admin', name: 'app_profile_admin')]
    public function profileAdmine(UserRepository $userRepository,Request $request){
        $us = $this->getUser();
        return $this->render('user/profileAdmine.html.twig',[
            'user' => $us
         ]);
    }
    #[Route('/membre', name: 'app_membre')]
    public function home(UserRepository $userRepository,Request $request,PeintureRepository $peintureRepository,MusiqueRepository $musiqueRepository): Response
    {
        $peinturesDB = $peintureRepository->findAll();
        $musiquesDB = $musiqueRepository->findAll();
            return $this->render('user/frontMembre.html.twig',[
                'peintures' => $peinturesDB,
                'Musiques' => $musiquesDB,]);

    }    
    
    
    #[Route('/login', name: 'app_forgot_password')]
    public function forgotpassword(): Response
    {
        return $this->render('security/login.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }
    #[Route('/user/list', name: 'app_user_list')]
    public function listuser(UserRepository $userRepository){
        $userBD = $userRepository->findAll();
        $user=$this->getUser();
        return $this->render('user/list.html.twig',[
            'users' => $userBD,
            'user'=>$user
        ]);
    }
    #[Route('/ajouter', name: 'app_user_new')]
    public function AjouterUser(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $us=$this->getUser();
        $form = $this->createForm(AddUserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var string $plainPassword */
            $plainPassword = $form->get('plainPassword')->getData();

            // encode the plain password
            $user->setPassword($userPasswordHasher->hashPassword($user, $plainPassword));

            $entityManager->persist($user);
            $entityManager->flush();

            // do anything else you need here, like send an email

            return $this->redirectToRoute('app_user_list');
        }

        return $this->render('user/form.html.twig', [
            'form' => $form,
            'user'=>$us
            
        ]);
    }
    #[Route('/profile', name: 'app_profile')]
    public function profile(UserRepository $userRepository,Request $request){
        $user = $this->getUser(); // Récupérer l'utilisateur connecté
        return $this->render('user/profile.html.twig',[
            'user' => $user
         ]);
    }
    
    #[Route('/user/edit/{id}', name: 'app_user_edit')]
    public function edituser($id, Request $request,EntityManagerInterface $em, UserRepository $userRepository){
        $user= $userRepository->find($id);
        $us=$this->getUser();
        $form= $this->createForm(EditUserType::class,$user);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            //$em->persist($user);
            $em->flush();
            return $this->redirectToRoute('app_user_list');
        }
        return $this->render('user/formEditUser.html.twig',[
            'title' => 'Update user',
            'form'=> $form,
            'user'=>$us
        ]);
    }
    #[Route('/user/remove/{id}', name: 'app_user_remove')]
public function removeuser($id, UserRepository $userRepository, EntityManagerInterface $em, Request $request, TokenStorageInterface $tokenStorage)
{
    $user = $userRepository->find($id);
    if ($user === $this->getUser()) {
        $tokenStorage->setToken(null);  
        $request->getSession()->invalidate();
        $em->remove($user);
        $em->flush();
        return $this->redirectToRoute('app_login');
    }
    $em->remove($user);
    $em->flush();
    return $this->redirectToRoute('app_user_list');
}
    
    #[Route('/change-password', name: 'app_change_password')]
    public function changePassword(Request $request, UserPasswordHasherInterface $passwordHasher, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();


        if ($request->isMethod('POST')) {
            $newPassword = $request->request->get('new_password');
            if (!empty($newPassword)) {
                $hashedPassword = $passwordHasher->hashPassword($user, $newPassword);
                $user->setPassword($hashedPassword);
                $entityManager->flush();

                $this->addFlash('success', 'Mot de passe modifié avec succès.');
                return $this->redirectToRoute('app_profile');
            }
        }

        return $this->render('user/change_password.html.twig');
    }

       #[Route('/profile/delete', name: 'app_delete_profile', methods: ['POST'])]
    public function deleteProfile(Request $request,EntityManagerInterface $entityManager): RedirectResponse
    {
        $user = $this->getUser();

        if ($user) {
            // Supprimer l'utilisateur de la base de données
            $this->entityManager->remove($user);
            $this->entityManager->flush();

            // Déconnexion de l'utilisateur après la suppression
            $this->get('security.token_storage')->setToken(null);
            $request->getSession()->invalidate();

            // Rediriger vers la route de déconnexion
            return $this->redirectToRoute('app_logout');
        }

        // Si l'utilisateur n'existe pas ou une erreur, retourner au profil
        return $this->redirectToRoute('app_profile');
    }
    #[Route('/profile/edit', name: 'app_profile_edit')]
    public function editProfile(Request $request, EntityManagerInterface $em)
    {
        // Récupérer l'utilisateur connecté
        $user = $this->getUser();

        // Créer le formulaire avec les données de l'utilisateur
        $form = $this->createForm(ModifierProfileType::class, $user);

        // Traiter la requête du formulaire
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($user);
            $em->flush();
            $this->addFlash('success', 'Profile updated successfully!');
            return $this->redirectToRoute('app_profile');
        }
        return $this->render('user/edit_profile.html.twig', [
            'form' => $form->createView(),
            'user' =>$user
        ]);
    }
    #[Route('/profileadmin/edit', name: 'app_profile_admin_edit')]
    public function editProfileAdmin(Request $request, EntityManagerInterface $em)
    {
        $user = $this->getUser();
        $form = $this->createForm(ModifierProfileAdminType::class, $user);
        $form->handleRequest($request);
        $us=$this->getUser();
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($user);
            $em->flush();
            $this->addFlash('success', 'Profile updated successfully!');
            return $this->redirectToRoute('app_profile_admin');
        }
        return $this->render('user/edit_profile_admin.html.twig', [
            'form' => $form->createView(),
            'user'=>$us

        ]);
    }
    #[Route('/search', name: 'user_search', methods: ['POST'])]
        public function search(Request $request, UserRepository $userRepository): Response
        {
            $query = $request->request->get('query'); // Récupérer la valeur du champ de recherche
            
            $users = $userRepository->searchByKeyword($query);

            return $this->render('user/list.html.twig', [
                'users' => $users,
            ]);
        }
        #[Route('/Afficherpa', name: 'app_peinture_afficher')]
        public function listPeinture(PeintureRepository $peintureRepository,MusiqueRepository $musiqueRepository)
        {
            $musiquesDB = $musiqueRepository->findAll();
            $peinturesDB = $peintureRepository->findAll();
            return $this->render('user/ListePeinture.html.twig', [
                'peintures' => $peinturesDB,
                'Musiques' => $musiquesDB
            ]);
        }
        #[Route('/style/afficher', name: 'app_style_afficher')]
        public function listStyle(StyleRepository $styleRepository,PeintureRepository $peintureRepository,MusiqueRepository $musiqueRepository){
            $stylesDB= $styleRepository->findAll();

templates/user/AfficherStile.html.twig
{% extends 'base.html.twig' %}

{% block title %}🎭 Galerie des Styles{% endblock %}

{% block body %}
{{parent()}}
    <h1 class="text-center mb-4">🎨 Galerie des Styles</h1>

    <div class="text-center mb-4">
        {# <a href="{{ path('app_style_new') }}" class="btn btn-success shadow-lg btn-lg rounded-pill">
            ➕ Ajouter un Style
        </a> #}
    </div>

    {% if styles is defined and styles is not empty %}
    <div class="row justify-content-center">
        {% for style in styles %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-lg">
                    <img src="{{ asset('uploads/photosP/' ~ style.extab) }}" alt="{{ style.extab }}" class="card-img-top"
                         style="height: 300px; object-fit: contain; background-color: #f8f9fa;">
                    <div class="card-body text-center">
                        <h5 class="card-title text-uppercase">{{ style.typep }}</h5>
                        <p class="card-text">{{ style.description }}</p>
                            <a href="{{ path('app_style_details_base', {id: style.id}) }}" class="btn btn-primary btn-lg shadow-sm rounded-pill mb-2">
                                📜 Détails
                            </a>
                        </div>
                    
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <p class="text-center mt-4">Aucun style disponible.</p>
    {% endif %}
</div>

<!-- Styles personnalisés -->
<style>
    .btn {
        font-size: 1rem;
        font-weight: 600;
        transition: transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out;
    }

    .btn:hover {
        transform: scale(1.08);
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);
    }

    .d-flex.flex-wrap {
        gap: 4.5px;
    }
</style>
{% endblock %}

templates/user/ListePeinture.html.twig
{% extends 'base.html.twig' %}

{% block title %}Galerie des Peintures{% endblock %}

{% block body %}
{{parent()}}
<div class="container mt-5">
    <h1 class="text-center mb-4">🎨 Galerie des Peintures</h1>

   {#  <div class="text-center mb-4">
        <a href="{{ path('app_peinture_new') }}" class="btn btn-success shadow-lg btn-lg rounded-pill">
            ➕ Ajouter une Peinture
        </a>
    </div> #}

    {% if peintures is defined and peintures is not empty %}
    <div id="peintureCarousel" 
         data-bs-ride="carousel" style="max-width: 900px; margin: auto;">
        <div class="carousel-inner">
            {% for peinture in peintures %}
                <div class="carousel-item {% if loop.first %}active{% endif %}">
                    <div class="d-flex justify-content-center">
                        <div class="card mb-4 shadow p-3 bg-light rounded" style="width: 35rem;">
                            <img src="{{ asset('uploads/photosP/' ~ peinture.tableau) }}" alt="{{ peinture.tableau }}" 
                                 class="card-img-top rounded" style="height: 300px; object-fit: contain; background-color: #f8f9fa;">
                            <div class="card-body text-center">
                                <h3 class="card-title">{{ peinture.titre | upper }}</h3>
                               {#  <p class="card-text">
                                    <b>Date de création :</b> {{ peinture.dateCr | date('d-m-Y') }} <br>
                                    <b>Type :</b> {{ peinture.type.typep }}
                                </p> #}
                                {# <div class="d-flex justify-content-center gap-4 mt-4">
                                    <a href="{{ path('app_peinture_edit', {id: peinture.id}) }}" class="btn btn-warning btn-lg shadow-sm rounded-pill">
                                        ✏ Modifier
                                    </a>
                                    <a href="{{ path('app_peinture_remove', {id: peinture.id}) }}" class="btn btn-danger btn-lg shadow-sm rounded-pill">
                                        🗑 Supprimer
                                    </a>
                                    <a href="{{ path('app_peinture_details', {id: peinture.id}) }}" class="btn btn-primary btn-lg shadow-sm rounded-pill">
                                        📜 Détails
                                    </a>
                                </div> #}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Boutons de navigation modernisés -->
        {# <button class="carousel-control-prev" type="button" data-bs-target="#peintureCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#peintureCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
        </button> #}
    </div>
    {% else %}
        <p class="text-center mt-4">Aucune peinture disponible.</p>
    {% endif %}
</div>

<!-- Styles personnalisés -->
<style>
    .carousel-control-prev-icon, .carousel-control-next-icon {
        background-color: green;
        border-radius: 50%;
        width: 40px;
        height: 40px;
    }

    .carousel-control-prev, .carousel-control-next {
        width: 5%;
    }

    .btn {
        font-size: 1rem;
        font-weight: 600;
        transition: transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out;
    }

    .btn:hover {
        transform: scale(1.08);
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);
    }

    .carousel {
        background-color: #f9f9f9; /* Légèrement gris clair */
        padding: 20px;
        border-radius: 15px;
    }
</style>

<!-- Script pour activer le carrousel immédiatement -->
<script>
    document.addEventListener("DOMContentLoaded", function() {
        new bootstrap.Carousel(document.getElementById('peintureCarousel'), {
            interval: 2500,
            pause: false, 
            wrap: true
        });
    });
</script>

<div class="container mt-5"> 


    <div class="row justify-content-center">
        {% if peintures is defined and peintures is not empty %}
            {% for peinture in peintures %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-lg">
                        <img src="{{ asset('uploads/photosP/' ~ peinture.tableau) }}" alt="{{ peinture.titre }}" class="card-img-top" style="height: 300px; object-fit: contain;">
                        <div class="card-body text-center">
                            <p class="card-text"><b>Titre :</b> {{ peinture.titre }}</p>
                            <p class="card-text"><b>Date de création :</b> {{ peinture.dateCr | date('d-m-Y') }}</p>
                            <p class="card-text"><b>Type :</b> {{ peinture.type.typep }}</p>
                          
                            <a href="{{ path('app_peinture_details_base', {id: peinture.id}) }}" class="btn btn-primary btn-lg shadow-sm rounded-pill"> 📜 Détails</a>   
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p class="text-center mt-4">Aucune peinture disponible.</p>
        {% endif %}
    </div>
</div>


{% endblock %}

templates/user/details_peinture_afficher.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de la Peinture{% endblock %}

{% block body %}
{{parent()}}
<div class="container mt-4">
    <div class="card shadow-sm">
        <div class="card-body text-center">
            {% if peinture.tableau %}
                <img src="{{ asset('uploads/photosP/' ~ peinture.tableau) }}" alt="{{ peinture.titre }}" class="img-fluid rounded" style="max-height: 400px;">
            {% else %}
                <p class="text-muted">Aucune image disponible</p>
            {% endif %}
            <h2 class="mt-3">{{ peinture.titre | upper }}</h2>
            <p class="card-text"><b>Date de création :</b> {{ peinture.dateCr | date('d-m-Y') }}</p>
            <p class="card-text"><b>Type :</b> {{ peinture.type.typep }}</p>
            <p class="card-text"><b>Description de ce type :</b> {{ peinture.type.description }}</p>
        </div>
    </div>
</div>
{% endblock %}

templates/user/details_style_afficher.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails de la Style{% endblock %}

{% block body %}
<nav class="main-nav-one stricky main-nav-one__home-two">
            <div class="container">
                <div class="inner-container">
                    <div class="logo-box">
                        <a href={{path('app_base')}}>
                            <img src="assets/images/o.png" alt width="143">
                        </a>
                        <a href="#" class="side-menu__toggler"><i class="muzex-icon-menu"></i></a>
                    </div><!-- /.logo-box -->
                    <div class="main-nav__main-navigation">
                        <ul class="main-nav__navigation-box">
                            <li class="dropdown">
                                <a href="#">Gestion Peinture</a>
                                <ul>
                                    <li><a href={{ path('app_peinture_new')}}> Ajouter les peinture</a></li>
                                    <li><a href={{ path('app_peinture_list')}}>Liste des peinture</a></li>
                                    <li><a href={{ path('app_style_new')}}>Ajouter les style</a></li>
                                    <li><a href={{ path('app_style_list')}}>Liste des styles</a></li>
                                </ul>
                            </li>
                          
                        </ul><!-- /.main-nav__navigation-box -->
                    </div><!-- /.main-nav__main-navigation -->
                   {#  <div class="main-nav__right">
                        <a href="#" class="search-popup__toggler"><i class="muzex-icon-search"></i></a>
                        <a class="sidemenu-icon side-content__toggler" href="#"><i class="muzex-icon-menu"></i></a>
                    </div><!-- /.main-nav__right --> #}
                </div><!-- /.inner-container -->
            </div><!-- /.container -->
        </nav>
<div class="container mt-4">
    <div class="card shadow-sm">
        <div class="card-body text-center">
            {% if style.extab %}
                <img src="{{ asset('uploads/photosP/' ~ style.extab) }}" alt="{{ style.extab }}" class="img-fluid rounded" style="max-height: 400px;">
            {% else %}
                <p class="text-muted">Aucune image disponible</p>
            {% endif %}
            <h2 class="mt-3">{{ style.typep | upper }}</h2>
            <p class="card-text"><b>Description de ce type :</b>{{ style.description }}</p>
            <p class="card-text"><b>Nombre de tableau posés de ce type : </b>{{ style.peintures | length }}</p>
        </div>
    </div>
</div>
{% endblock %}

templates/user/edit_profile_admin.html.twig
{% extends 'profil.html.twig' %}

{% block title %}Ajouter un Compte{% endblock %}

{% block body %}
{{parent()}}
    <div class="container">
        <div class="card shadow p-4">
            <h2 class="text-center mb-4">Éditer un Utilisateur</h2>
            {{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}
            
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_label(form.nom) }}
                        {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_label(form.prenom) }}
                        {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
            </div>

            <div class="form-group mt-3">
                {{ form_label(form.email) }}
                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group mt-3">
                {{ form_label(form.genre) }}
                {{ form_widget(form.genre, {'attr': {'class': 'form-select'}}) }}
            </div>

            <div class="form-group mt-3">
                {{ form_label(form.plainPassword) }}
                {{ form_widget(form.plainPassword, {'attr': {'class': 'form-control'}}) }}
            </div>

            <fieldset class="mt-3">
                <legend>Rôles</legend>
                <div class="form-check">
                    {{ form_widget(form.roles, {'attr': {'class': 'form-check-label'}}) }}
                </div>
            </fieldset>

            <div class="form-check mt-3">
                {{ form_widget(form.agreeTerms, {'attr': {'class': 'form-check-input'}}) }}
                {{ form_label(form.agreeTerms) }}
            </div>

            <div class="text-center mt-4">
                {{ form_widget(form.Envoyer, {'attr': {'class': 'btn btn-primary'}}) }}
            </div>

            {{ form_end(form) }}
            
            <div class="mt-4 text-center">
                <a href="{{ path('app_profile_admin') }}">
                    <span>Retour à la Profile sans modification</span>
                </a>
            </div>
        </div>
    </div>

{% endblock %}